[build-system]
requires = ["flit_core >=3.2,<4", "myst-parser"]
build-backend = "flit_core.buildapi"

[project]
name = "vheliotech"
authors = [{name = "Velo solaire pour tous", email = "contact@vhelio.org"}]
dynamic = ["version", "description"]
